#!/bin/bash
# Copyright (C) 2021 MyGpack

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# error precaution.
set -e

WORK_DIR="userbot"
mkdir -p $WORK_DIR

disp () {
    echo "-----> $*"
}

indent () {
    sed -u 's/^/       /'
}

_done () {
    echo -e "Done\n" | indent
}

_displaylogo () {
    echo '
===========================================

  ▄████  ██▓███   ▄▄▄       ▄████▄   ██ ▄█▀
 ██▒ ▀█▒▓██░  ██▒▒████▄    ▒██▀ ▀█   ██▄█▒ 
▒██░▄▄▄░▓██░ ██▓▒▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ 
░▓█  ██▓▒██▄█▓▒ ▒░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄ 
░▒▓███▀▒▒██▒ ░  ░ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄
 ░▒   ▒ ▒▓▒░ ░  ░ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒
  ░   ░ ░▒ ░       ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░
░ ░   ░ ░░         ░   ▒   ░        ░ ░░ ░ 
      ░                ░  ░░ ░      ░  ░   
                           ░               
===========================================
|            VERSION  v0.1.0              |
|    By: @midnightmadwalk and code-rgb    |
|           (C) 2021 - USERGE-X           |
===========================================
'
}

_setup_repo () {git clone ${UPSTREAM_REPO} Venom-X}
_startbot () {
    local bot_dir
    bot_dir=$(cd $WORK_DIR && ls) && mv "$WORK_DIR/$bot_dir" "Venom-X"
    rm -rf $WORK_DIR
    cd "Venom-X"
    git init > /dev/null 2>&1
    echo -e ">><< --- >><<  Starting [X]  >><< --- >><<\n" | indent
    bash run
}

begin_x () {
    _displaylogo
    sleep 5
    _setup_repo
    _startbot
}

begin_x
