#!/bin/bash
# Copyright (C) 2021 MyGpack

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# error precaution.
_x{
    cd ~
}

_setup_repo () {
    local repo_path
    git clone $UPSTREAM_REPO -b $PREF_BRANCH /root/v
}
_startbot () {
    cd /root/v
    git init > /dev/null 2>&1
    echo -e ">><< --- >><<  Starting [X]  >><< --- >><<\n" | indent
    bash run
}

begin_x () {
    _setup_repo
    _startbot
}
_x
begin_x
